---
title: "Dashboard!!"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)

library(plotly)
```

```{r}
data("rest_inspec")
```

```{r}
rest_inspec = 
  rest_inspec |> 
  select(
    boro, inspection_date, score) |>
  filter(
    !is.na(score), 
    boro != "Missing")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
rest_inspec |>
  filter(boro %in% c("STATEN ISLAND","BRONX")) |>
  plot_ly(
    x = ~inspection_date, y = ~score, type = "scatter", mode = "markers",
    color = ~boro, colors = c("red", "blue"), alpha = 0.7)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
rest_inspec |> 
  mutate(boro = fct_reorder(boro, score)) |> 
  plot_ly(x= ~boro, y = ~score, color = ~boro, type = "box", colors = "viridis")
```

### Chart C

```{r}
rest_inspec |> 
  count(boro) |> 
  mutate(boro = fct_reorder(boro, n)) |> 
  plot_ly(x = ~boro, y = ~n, color = ~boro, type = "bar", colors = "viridis")
```

