---
title: "NYC Shooting Incident Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(DT)
library(plotly)
library(shiny)
library(forcats)
```

```{r}
df=read_csv("data_final.csv")
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
radioButtons(
  "borough_choice", 
  label = h3("Choose Borough"),
  choices = c("Manhattan","Brooklyn","Queens","Bronx","Staten Island"), selected = "Manhattan")
```

```{r}
year = df |> distinct(Year) |> arrange(desc(Year)) |> pull()

selectInput(
  "year_choice", 
  label = h3("Choose year"),
  choices = year, selected = "2022")
```

Column {data-width=700}
-----------------------------------------------------------------------

### Incident distribution on NYC map

```{r}
Sys.setenv('MAPBOX_TOKEN' = 'pk.eyJ1IjoiZWR3YXJkenp6IiwiYSI6ImNtNDkwMzZ3YTA1MGIyanE1ZjdlNTZodjcifQ.BsLSffH3a0z5Xqf1Tqc4ag') 

renderPlotly({
  center_coords <- switch(input$borough_choice,
                          "Manhattan" = list(lon = -73.95, lat = 40.785),
                          "Brooklyn" = list(lon = -73.945, lat = 40.65),
                          "Bronx" = list(lon = -73.884, lat = 40.85),
                          "Queens" = list(lon = -73.837, lat = 40.72),
                          "Staten Island" = list(lon = -74.159, lat = 40.58))
  
  incidents_filtered <- df %>%
    filter(neighbourhood_group == input$borough_choice,
           Year == input[["year_choice"]]) %>%
    drop_na(Sky_Is_Dark, Longitude, Latitude, NTA, OCCUR_TIME, OCCUR_DATE) |>
    mutate(Sky_Condition = ifelse(Sky_Is_Dark, "Night", "Day"))
  
  plot_ly(data = incidents_filtered, 
          type = "scattermapbox",       
          mode = "markers",             
          lon = ~Longitude,             
          lat = ~Latitude,              
          color = ~Sky_Condition,       
          colors = c("Day" = "orange", "Night" = "blue"), 
          marker = list(size = 5, opacity = 0.7),  
          text = ~paste("NTA:", NTA,
                        "<br>Date of Incident:", OCCUR_DATE,
                        "<br>Time of Incident:", OCCUR_TIME,
                        "<br>Sky Condition:", Sky_Condition)) |> 
    layout(
      mapbox = list(
        style = "carto-positron",      
        center = center_coords,        
        zoom = 9.5                    
      ),
      showlegend = TRUE,               
      legend = list(title = list(text = 'Sky Condition')))
})
```

### Top 10 NTAs with the highest Annual Incident Rate by Borough and Year

```{r}
renderPlotly({
  df_filtered <- df |>
    filter(
      neighbourhood_group == input[["borough_choice"]],
      Year == input[["year_choice"]],
      NTAType == "Residential"
    ) |>
    select(neighbourhood_group, Year, NTA, incident_rate_by_year_nta) |>
    distinct() |>
    rename(
      Borough = neighbourhood_group,
      Incident_rate = incident_rate_by_year_nta
    ) |>
    mutate(Incident_rate = signif(Incident_rate, 3)) |>  
    arrange(desc(Incident_rate)) |>
    head(10) |>
    mutate(NTA = fct_reorder(NTA, Incident_rate, .desc = TRUE)) 

  plot_ly(
    data = df_filtered,
    x = ~NTA,
    y = ~Incident_rate,
    type = 'bar',
    color = ~NTA,
    colors = "viridis"
  ) |>
    layout(
      xaxis = list(
        title = "NTA",
        showticklabels = FALSE
      ),
      yaxis = list(title = "Incident Rate")
    )
})
```

Column {data-width=500}
-----------------------------------------------------------------------

### NTA Incident Rate (from highest to lowest) Information by Borough and Year

```{r}
renderDataTable({
  top_10_nta <- df %>%
    filter(neighbourhood_group == input[["borough_choice"]],
           Year == input[["year_choice"]],
           NTAType == "Residential") %>% 
    group_by(BORO, Year, NTA) %>%
    summarise(total_incidents = n(),
              total_population = first(Total_population_nta),
              percent_poverty = first(Percent_poverty),
              percent_education = first(Percent_education)) %>%
    mutate(incident_rate = (total_incidents / total_population) * 100) %>%  
    arrange(desc(incident_rate)) %>%  
    ungroup() %>%
    select(NTA, incident_rate, total_incidents, total_population, percent_poverty, percent_education)
})
```
